$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: iris-deployment
endpoint_name: iris-endpoint
model: azureml:iris-classifier@latest
code_configuration:
  code: ../data-science/src
  scoring_script: score.py
environment: azureml:iris-train-env@latest
instance_type: Standard_DS2_v2
instance_count: 1
